export const CREATIVE_FIELDS = {
  popular: [
    "Architecture", "Art Direction", "Branding", "Fashion", "Graphic Design",
    "Illustration", "Industrial Design", "Interaction Design", "Logo Design",
    "Motion Graphics", "Photography", "UI/UX", "Web Design",
  ],
  all: [
    "3D Art", "3D Modeling", "3D Motion",
    "Advertising", "Advertising Photography", "Animation", "App Design", "Apparel",
    "AR/VR", "Architecture", "Architecture Concept", "Architecture Photography",
    "Architecture Visualization", "Art Direction", "Automotive Design",
    "Beauty Photography", "Branding",
    "Calligraphy", "CGI", "Character Design", "Cinematography", "Collage", "Coloring",
    "Comic", "Concept Art", "Copywriting", "Costume Design", "Crafts",
    "Creative Direction", "Culinary Arts",
    "Digital Art", "Digital Painting", "Directing", "Drawing",
    "Editing", "Editorial Design", "Education", "Environmental Graphics", "Exhibition Design",
    "Fashion", "Fashion Design", "Fashion Illustration", "Fashion Photography",
    "Fashion Retouching", "Fashion Styling", "Film", "Fine Arts", "Flower Arrangement",
    "Food Photography", "Food Styling", "Furniture Design",
    "Game Design", "GIF Animation", "Graffiti", "Graphic Design",
    "Icon Design", "Illustration", "Industrial Design", "Infographic",
    "Information Architecture", "Interaction Design", "Interior Design",
    "Jewelry Design",
    "Label Design", "Landscape Design", "Lettering", "Logo Design",
    "Makeup", "Makeup Arts", "Model Test Photography", "Modeling", "Motion Graphics",
    "Music", "Music Packaging",
    "Packaging", "Painting", "Paperworks", "Pattern Design", "Performing Arts",
    "Photography", "Photography Styling", "Photojournalism", "Poster Design",
    "Product Design", "Product Photography", "Programming", "Projection Mapping", "Props Design",
    "Retouching",
    "Sculpting", "Set Design", "Shoe Design", "Sketching", "Sound Design",
    "Storyboarding", "Street Art", "Styleframing", "Surface Design",
    "T-Shirt Design", "Textile Design", "Toy Design", "Type Design", "Typography",
    "UI/UX",
    "Visual Effects", "Visualization",
    "Web Design", "Window Design", "Woodworking", "Writing",
  ],
}
